apiVersion: apps/v1
kind: Deployment
metadata:
  name: finsync-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finsync
  template:
    metadata:
      labels:
        app: finsync
    spec:
      containers:
      - name: finsync-container
        # I filled in your real Account ID (279606006025) and Region (us-east-1)
        # Note: Your Jenkins pipeline will automatically overwrite the ':latest' tag 
        # with the specific build number (e.g., :5) during deployment.
        image: 279606006025.dkr.ecr.us-east-1.amazonaws.com/finsync-repo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: finsync-service
spec:
  type: LoadBalancer
  selector:
    app: finsync
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
